name: Michael's flow

on:
  push:
    branches: 'main'
    workflow-dispatch:

jobs:
  dockerBuildPush:
    runs-on: ubuntu-latest
    steps:

      - name: QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: BuildPush
        uses: docker/build-push-action@v4
        with: 
          context: "{{defaultContext}}:website"
          push: true
          tags: dmichael29/project4:latest  
